import RPi.GPIO as GPIO
from water_distribution_system import (
    INT1, RS1, RS2, RS3, ECHO_RESPONSE_0, PWR_PUMP1, PWR_PUMP2, PWR_PUMP3, PWR_PUMP4,
    TRIGGER_0, LCD_PWM, LCD_RST, BUZZER, ENABLE_ALARM1, ENABLE_ALARM2
)

def GPIO_setup():
    IN_PINS = [INT1, RS1, RS2, RS3, ECHO_RESPONSE_0]
    OUT_PINS = [PWR_PUMP1, PWR_PUMP2, PWR_PUMP3, PWR_PUMP4, TRIGGER_0, LCD_PWM, LCD_RST, BUZZER, ENABLE_ALARM1, ENABLE_ALARM2]

    for pin in IN_PINS:
        GPIO.setup(pin, GPIO.IN)

    for pin in OUT_PINS:
        GPIO.setup(pin, GPIO.OUT)